drop table if exists students_courses CASCADE;
drop table if exists groups CASCADE;
drop table if exists courses CASCADE;
drop table if exists students CASCADE;

create table groups (
	group_id int4 not null generated by default as identity,
	group_name varchar(255) not null,
	constraint groups_pkey primary key (group_id)
);

create table students (
	student_id int4 not null generated by default as identity,
	group_id int4 null,
	first_name varchar(255) not null,
	last_name varchar(255) not null,
	constraint students_pkey primary key (student_id),
	constraint students_fk foreign key (group_id) references groups(group_id) on delete cascade
);

create table courses (
	course_id int4 not null generated by default as identity,
	course_name varchar(255) not null,
	course_description varchar(500) not null,
	constraint courses_pkey primary key (course_id)
);

create table students_courses (
	student_id int4 not null,
	course_id int4 not null,
	constraint pk_studentsincourses primary key (student_id, course_id),
	constraint studentsincourses_fk foreign key (student_id) references students(student_id) on delete cascade,
	constraint studentsincourses_fk2 foreign key (course_id) references courses(course_id) on delete cascade
);
