DROP TABLE if EXISTS students_courses CASCADE;
DROP TABLE if EXISTS groups CASCADE;
DROP TABLE if EXISTS courses CASCADE;
DROP TABLE if EXISTS students CASCADE;

CREATE TABLE groups (
	group_id int4 NOT NULL generated BY DEFAULT AS identity,
	group_name VARCHAR(255) NOT NULL,
	CONSTRAINT groups_pkey PRIMARY KEY (group_id)
);

CREATE TABLE students (
	student_id int4 NOT NULL generated BY DEFAULT AS identity,
	group_id int4 NULL,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	CONSTRAINT students_pkey PRIMARY KEY (student_id),
	CONSTRAINT students_fk FOREIGN KEY (group_id) REFERENCES groups(group_id) ON DELETE CASCADE
);

CREATE TABLE courses (
	course_id int4 NOT NULL generated BY DEFAULT AS identity,
	course_name VARCHAR(255) NOT NULL,
	course_description VARCHAR(500) NOT NULL,
	CONSTRAINT courses_pkey PRIMARY KEY (course_id)
);

CREATE TABLE students_courses (
	student_id int4 NOT NULL,
	course_id int4 NOT NULL,
	CONSTRAINT pk_studentsincourses UNIQUE (student_id, course_id),
	CONSTRAINT studentsincourses_fk FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE,
	CONSTRAINT studentsincourses_fk2 FOREIGN KEY (course_id) REFERENCES courses(course_id) ON DELETE CASCADE
);
